server:
  port: 8040

# 应用名称
spring:
  application:
    name: newbee-mall-cloud-shop-cart-web
  # 连接nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #      username: nacos
  #      password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_cart_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: li970511