server:
  port: 8010

# 应用名称
spring:
  application:
    name: newbee-mall-cloud-goods-web
# 连接nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#      username: nacos
#      password: nacos
#  连接数据库
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_goods_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: li970511

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

