server:
  port: 8000

# 应用名称
spring:
  application:
    name: newbee-mall-cloud-gateway-admin
  # 连接nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#      username: nacos
#      password: nacos
  ## 连接Redis数据库
  redis:
    ## Redis数据库索引（默认为0）
    database: 13
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码
    # password:
