server:
  port: 8050

# 应用名称
spring:
  application:
    name: newbee-mall-cloud-user-web
  # 连接nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #      username: nacos
  #      password: nacos
  ## 连接Mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_user_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: li970511
  ## 连接Redis数据库
  redis:
    ## Redis数据库索引（默认为0）
    database: 13
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码
    # password:

